name: Tests

on:
  push:
  pull_request:

jobs:
  build-and-run-unit-tests:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: [ Debug, Release ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.9.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          modules: "qtmultimedia"
          cache: true

      - name: Configure CMake
        run: cmake -S . -B build/${{ matrix.config }} -DCMAKE_PREFIX_PATH="${{ env.QT_ROOT_DIR }}"

      - name: Build (${{ matrix.config }})
        run: cmake --build build/${{ matrix.config }} --config ${{ matrix.config }}

      - name: Run unit tests (${{ matrix.config }})
        run: ctest --test-dir build/${{ matrix.config }} --output-on-failure -C ${{ matrix.config }}
